__title__ = "prophet"
__description__ = "Automatic Forecasting Procedure"
__url__ = "https://facebook.github.io/prophet/"
__version__ = "1.1.1"
__author__ = "Sean J. Taylor <sjtz@pm.me>, Ben Letham <bletham@fb.com>"
__author_email__ = "sjtz@pm.me"
__license__ = "MIT"
